name: mobile_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_riverpod: ^2.5.1
  shimmer: ^3.0.0
  
  dio: ^5.4.3+1
  fl_chart: ^0.68.0
  intl: ^0.19.0 # Version plus standard
  screenshot: ^3.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.5
  share_plus: 10.1.4 # CHANGEMENT ICI : Version stable pour Ã©viter les erreurs Kotlin

  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  get_test: ^4.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  
flutter:
  uses-material-design: true
